name: My First CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show Current Dir
        run:  pwd

      - name: List files
        run: ls -la

      - name: print message
        run: echo "CI/CD is working"  
